x-vllm-common: &vllm-common
  image: vllm/vllm-openai:v0.19.1   # vllm-openai容器镜像
  restart: unless-stopped
  gpus: all
  ipc: host
  environment:
    HF_TOKEN: ""  # Huggingface Token，用于解除下载模型的速率限制
    HF_HUB_OFFLINE: '1'
    VLLM_SERVER_DEV_MODE: "1"   # 用于模型的 sleep/wake 能力，以动态释放显存
  volumes:
    - ~/.cache/huggingface:/root/.cache/huggingface
    - ./scripts/vllm-init-sleep-check.py:/vllm-init-sleep-check.py:ro
  networks:
    - chip_testing_flowcard_generator
  healthcheck:
    test: ["CMD", "curl", "-fsS", "http://127.0.0.1:18080/health"]
    interval: 3s
    timeout: 3s
    retries: 100
    start_period: 30s
  post_start:
    - command: >
        sh -lc '
        nohup python3 /vllm-init-sleep-check.py >/dev/null 2>&1 &
        exit 0
        '

services:
  milvus-etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.25
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    expose:
      - "2379"
    volumes:
      - ./volume/milvus-etcd:/etcd
    networks:
      - chip_testing_flowcard_generator
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus-minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    expose:
      - "9000"
      - "9001"
    volumes:
      - ./volume/milvus-minio:/minio_data
    networks:
      - chip_testing_flowcard_generator
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.6.8
    command: [ "milvus", "run", "standalone" ]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MQ_TYPE: woodpecker
    volumes:
      - ./volume/milvus:/var/lib/milvus
    networks:
      - chip_testing_flowcard_generator
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    expose:
      - "19530"
      - "9091"
    depends_on:
      - "milvus-etcd"
      - "milvus-minio"

  vllm-llm:
    <<: *vllm-common
    container_name: vllm-llm
    entrypoint: ["vllm", "serve"]
    command:  # Qwen/Qwen3.6-35B-A3B-FP8 模型的定制化参数
      - "Qwen/Qwen3.6-35B-A3B-FP8"
      - "--served-model-name"
      - "Qwen/Qwen3.6-35B-A3B-FP8"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--reasoning-parser"
      - "qwen3"
      - "--language-model-only"
      - "--max-model-len"
      - "96K"
      - "--gpu-memory-utilization"
      - "0.84"
      - "--enable-sleep-mode"
      - "--enable-chunked-prefill"
      - "--max-num-batched-tokens"
      - "4096"
      - "--max-num-seqs"
      - "4"
    #      - "--api-key"
    #      - ""
    #      - "--enable-auto-tool-choice"
    #      - "--tool-call-parser"
    #      - "qwen3_coder"
    expose:
      - "8000"

  vllm-embedding:
    <<: *vllm-common
    container_name: vllm-embedding
    entrypoint: ["vllm", "serve"]
    command:  # Qwen/Qwen3-Embedding-0.6B 模型的定制化参数
      - "Qwen/Qwen3-Embedding-0.6B"
      - "--served-model-name"
      - "Qwen/Qwen3-Embedding-0.6B"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--runner"
      - "pooling"
      - "--max-model-len"
      - "8K"
      - "--gpu-memory-utilization"
      - "0.1"
      - "--enable-sleep-mode"
    #      - "--api-key"
    #      - "${VLLM_API_KEY}"
    depends_on:
      vllm-llm:
        condition: service_healthy
    expose:
      - "8000"

  vllm-reranker:
    <<: *vllm-common
    container_name: vllm-reranker
    entrypoint: ["vllm", "serve"]
    command:  # Qwen/Qwen3-Reranker-0.6B 模型的定制化参数
      - "Qwen/Qwen3-Reranker-0.6B"
      - "--served-model-name"
      - "Qwen/Qwen3-Reranker-0.6B"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--runner"
      - "pooling"
      - "--max-model-len"
      - "8K"
      - "--gpu-memory-utilization"
      - "0.1"
      - "--enable-sleep-mode"
      - "--hf-overrides"
      - '{"architectures":["Qwen3ForSequenceClassification"],"classifier_from_token":["no","yes"],"is_original_qwen3_reranker":true}'
      - "--chat-template"
      - "/opt/templates/qwen3_reranker.jinja"
    #      - "--api-key"
    #      - "${VLLM_API_KEY}"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./scripts/vllm-init-sleep-check.py:/vllm-init-sleep-check.py:ro
      - ./volume/vllm-reranker/templates:/opt/templates:ro
    depends_on:
      vllm-embedding:
        condition: service_healthy
    expose:
      - "8000"

  backend:
    container_name: backend
    image: backend  # 需要自行构建
    volumes:
      - ./volume/backend/flowcard:/app/flowcard
      - ./volume/backend/log:/app/log
      - ./volume/backend/storage:/app/storage
      - ./volume/backend/config.toml:/app/config.toml:ro
    networks:
      - chip_testing_flowcard_generator
    expose:
      - "9000"
    depends_on:
      vllm-llm:
        condition: service_healthy
      vllm-embedding:
        condition: service_healthy
      vllm-reranker:
        condition: service_healthy
      milvus:
        condition: service_healthy

  frontend:
    container_name: frontend
    image: frontend  # 需要自行构建
    networks:
      - chip_testing_flowcard_generator
    expose:
      - "80"
    ports:
      - "8080:80"
    depends_on:
      - "backend"

networks:
  chip_testing_flowcard_generator:
    driver: bridge
